name: Test Verification

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Init submodules
      run: git submodule update --init --recursive
    - name: Build the Docker image
      run: docker build . --file .ci/Dockerfile.ubuntu --tag ubuntu_debugimage:latest
    - name: Run tests
      run: docker run ubuntu_debugimage:latest ctest /build --output-on-failure
  build-windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - name: Init submodules
      run: git submodule update --init --recursive
    - name: Build the Docker image
      run: docker build . --file .ci/Dockerfile.windows --tag windows_debugimage:latest
